theme: jekyll-theme-so-simple
skin: "/assets/css/skins/dark.css"

locale: en-US
title: Alex Lehner
description: Engineer and occasional juggler
logo: images/alex-lehner.jpg
date_format: "%B %-d, %Y"

read_time: true
words_per_minute: 175

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: UA-39319867-2

twitter:
  username: alexjlehner

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

# Search
search_full_content: false # can have performance implications for large sites

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: false

# Site Author
author:
  name: Alex Lehner
  email: alex@alexlehner.com
  twitter: alexjlehner

# Footer Links
footer_links:
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
